### ISSUE TITLE
[Perf] Some iterator method can be improved by using internal method

### ISSUE THREAD

**Issue by KarryCharon** [crazytuzi/UnrealCSharp#129]
实际对性能影响未测试, 仅为猜测, Remove 和 Find 等可替换为 内置实现
1. int32 TGarbageCollectionHandleMapping<T>::Remove(const MonoObject* InKey)
2. MonoObject* FContainerRegistry::GetObject(const void* InAddress)
3. T* TGarbageCollectionHandleMapping<T>::Find(const MonoObject* InMonoObject)
4. bool FContainerRegistry::RemoveReference(const void* InAddress)
5. bool FDelegateRegistry::RemoveReference(const void* InAddress)

**Comment by crazytuzi** [comment]
此部分代码已重构。
