### ISSUE TITLE
support for .NET 8 and 9 prev

### ISSUE THREAD

**Issue by sekkit** [crazytuzi/UnrealCSharp#344]
as the title indicates, to enable AOT

**Comment by ram16g** [comment]
[.NET 7 will reach End of Support on May 14, 2024](https://devblogs.microsoft.com/dotnet/dotnet-7-end-of-support/)

**Comment by crazytuzi** [comment]
I have submitted support for .NET 8.0.5 and also written an article on how to compile Mono for multiple platforms.
-  [Add submodule Mono](https://github.com/crazytuzi/UnrealCSharp/commit/796c33f7632b0cf4ce012ba2fd9d926f6a8985f2)
- [compile](https://unrealcsharp.github.io/docs/document/advanced/compile)
