### ISSUE TITLE
UE5.4.3下启动引擎出错

### ISSUE THREAD

**Issue by huzhangyang** [crazytuzi/UnrealCSharp#383]
官方引擎+新工程，启动时挂在这里

尝试master分支和develop分支结果均相同

mono从这里取的：https://github.com/crazytuzi/Mono

![image](https://github.com/user-attachments/assets/91eefeee-d5b3-4333-8d60-0b8923f709b3)

**Comment by slb1988** [comment]
根据文档，安装微软官方.Net 8.0版本没发现问题

**Comment by crazytuzi** [comment]
参考[编译Mono](https://unrealcsharp.github.io/docs/document/advanced/compile)本地编译一份Mono，然后看具体Mono堆栈

**Comment by huzhangyang** [comment]
在另一台电脑上测试也是一样，并且Visual Studio Installer里确认安装了 .Net 8.0运行时，我试试编译Mono吧

**Comment by huzhangyang** [comment]
找到原因了，初始化Mono的方式不对，应该按照.gitmodules的配置放在Source\ThirdParty\Mono目录，我直接放在Source下了，可以通过编译但运行时报错。后续文档中感觉可以细化一下这里的说明
