### ISSUE TITLE
动态类的 ReceiveTick 无法被触发

### ISSUE THREAD

**Issue by tiagochen** [crazytuzi/UnrealCSharp#387]
`using System;
using Script.Dynamic;
using Script.Engine;

namespace Script.CoreUObject;

[UClass]
public partial class AMyActor : AActor
{
    public AMyActor()
    {
        PrimaryActorTick.bCanEverTick = true;
        Console.WriteLine("AMyActor Constructor!" + PrimaryActorTick.bCanEverTick);
    }
    
    [Override]
    public override void ReceiveBeginPlay()
    {
        base.ReceiveBeginPlay();
        Console.WriteLine("ReceiveBeginPlay!");
    }
    
    [Override]
    public override void ReceiveTick(float time)
    {
        base.ReceiveTick(time);
        Console.WriteLine("ReceiveTick: " + time);
    }
}`

直接spawn 这个类，ReceiveBeginPlay 的日志可以正常输出， ReceiveTick 不会被触发。

**Comment by huzhangyang** [comment]
我这里测了下没出现这问题，ReceiveTick每帧正常打印log

**Comment by tiagochen** [comment]
> 我这里测了下没出现这问题，ReceiveTick每帧正常打印log

![image](https://github.com/user-attachments/assets/d1c632b6-fbc3-4267-99d3-38f4c9d8cee3)

**Comment by crazytuzi** [comment]
动态蓝图类没问题，动态C++类不行，究其原因的话，是引擎自身源码限制[AActor::Tick](https://github.com/EpicGames/UnrealEngine/blob/release/Engine/Source/Runtime/Engine/Private/Actor.cpp#L1497)，[UActorComponent::TickComponent](https://github.com/EpicGames/UnrealEngine/blob/release/Engine/Source/Runtime/Engine/Private/Components/ActorComponent.cpp#L1345)。

**Comment by tiagochen** [comment]
![ad81186cbe9a0127888cc7506ef02e1d](https://github.com/user-attachments/assets/0cff7dd1-6f93-4357-86a3-178e29d184a0)
改用这个动态蓝图类的方式
