### ISSUE TITLE
c#自定义角色组件在蓝图界面找不到

### ISSUE THREAD

**Issue by tiagochen** [crazytuzi/UnrealCSharp#388]
问题截图如下： 

![image](https://github.com/user-attachments/assets/48419d2a-a798-49e8-ab04-ba792cff5d42)

![image](https://github.com/user-attachments/assets/ee1ebfb5-e173-4a63-b7f4-91bc78478001)

![image](https://github.com/user-attachments/assets/67fabfea-eeae-4e07-93fc-2b3d3213c785)

**Comment by tiagochen** [comment]
UObject 及其子类有相同的问题：

![559d7fa5a290d085d64ab8b978631f3f](https://github.com/user-attachments/assets/55cadd14-e874-47f2-a2d6-cc3a31760dc5)
![e9fc2a128bb7f4c62a51a1823a245691](https://github.com/user-attachments/assets/efee0ca2-4d88-4afd-a981-af89774ecb47)
![faab792534d8e670a6914860f78fb687](https://github.com/user-attachments/assets/9d21fa08-d0f6-47cb-8d2c-947d911f7ae2)

**Comment by crazytuzi** [comment]
```csharp
using Script.Dynamic;

namespace Script.CoreUObject
{
    [UClass, Blueprintable, BlueprintType, IsBlueprintBase("true")]
    public partial class UTestDynamicObject : UObject
    {
    }
}
```
