### ISSUE TITLE
C#对象的析构函数会在异步线程执行

### ISSUE THREAD

**Issue by UnrealKiller** [crazytuzi/UnrealCSharp#409]
假如基础开发框架是在C#这边，在功能上很多情况下可能会存在UE对象的生命周期需要跟随某个C#对象的生命周期，因为C#的这个机制，就意味着在析构函数中一定不能去写UObject对象的操作逻辑，但很多时候又需要一个结束时机，现在的情况就是处理这种情况只能手动调用
目前手动增加了异步模块去处理
![9b18e261efb249440e1d135e9889b93d](https://github.com/user-attachments/assets/acb1fb84-e21b-4e45-bbf2-5a6dbe3f5cbd)

**Comment by crazytuzi** [comment]
这个和C#语言机制以及UE限制有关，更多希望的是，在类似ReceiveEndPlay或者Destruct这种UE提供的时间节点中去执行清理操作。
