### ISSUE TITLE
[BUG] ActorComponent C#实例里的 ReceiveTick 没有执行

### ISSUE THREAD

**Issue by cocochengang** [crazytuzi/UnrealCSharp#432]
UE： 5.4.4
UECsharp：v0.5.0

在蓝图Actor上挂了个 ActorComponent
![image](https://github.com/user-attachments/assets/d8682ce1-876b-49b0-813c-8b74c07bff81)

C# partial类里 覆盖了BeginPlay 和 Tick，ReceiveBeginPlay有执行，但ReceiveTick 没有执行，不明白哪里有问题？
![image](https://github.com/user-attachments/assets/4c2452aa-f019-48b9-b99d-56dee7a450d9)

**Comment by crazytuzi** [comment]
参考 #387

**Comment by cocochengang** [comment]
构造函数里，设置后，Tick 执行成功！
```
protected HeroCamCom_C(){
	PrimaryComponentTick.bCanEverTick = true;
}
```
