### ISSUE TITLE
C#中实现DataTable，在蓝图继承，设置其中任何字段都会导致崩溃

### ISSUE THREAD

**Issue by abimlopas** [crazytuzi/UnrealCSharp#433]
![7D9E1C64AEC7B8
![7D26B5C26FD521AB5E6836F44C4E4A0C](https://github.com/user-attachments/assets/83ee695a-8b25-4c3f-a3bd-4e4b17030945)
5F48ED5C0B6557BDC7](https://github.com/user-attachments/assets/61fc2e59-1c42-4a06-b02d-098b5fbf1cac)
![6DDD0E426E3F78CBEE606EE6DC6F5505](https://github.com/user-attachments/assets/df913e85-e624-46b4-ada3-ed3c4b84357f)
![1CFE50D8E504987B9EC40D8C50639473](https://github.com/user-attachments/assets/29d7ce54-5447-46c3-9968-772232c77306)
![7D26B5C26FD521AB5E6836F44C4E4A0C](https://github.com/user-attachments/assets/37342942-79a5-44bb-9bb6-cee40a199be3)

**Comment by crazytuzi** [comment]
namespace修改为Script.CoreUObject即可，目前如果namespace不是Script.CoreUObject预期会编译错误，可以先排查下本地Weavers为啥没生效。

**Comment by abimlopas** [comment]
![image](https://github.com/user-attachments/assets/91570fe0-d716-4816-b6f8-dc2b71bddf75)
namespace修改为Script.CoreUObject也不行，
![image](https://github.com/user-attachments/assets/8c567c59-840d-4729-849b-972ab4a5dc41)
使用[UnrealCSharpTest]工程测试也是一样的
