### ISSUE TITLE
C#中继承C++导出的类，覆盖父类的虚函数，子类覆盖的函数无法触发

### ISSUE THREAD

**Issue by abimlopas** [crazytuzi/UnrealCSharp#434]
![019F0F458768023020D39FB906274D18](https://github.com/user-attachments/assets/7a2635ac-234a-4688-863c-8a96961ab7b0)
![55A7181BB740CF8A960141657518091D](https://github.com/user-attachments/assets/5de50e11-5331-4446-8004-323c82c0bcce)

**Comment by crazytuzi** [comment]
[覆盖函数介绍](https://unrealcsharp.github.io/docs/document/getting-started/override#%E4%BB%8B%E7%BB%8D)
