### ISSUE TITLE
C#继承C++导出的UE类，如：GameMode、GameInstance、Character、UserWidget等经常会被识别成Actor或者不是显示在编辑器的BlueprintClass

### ISSUE THREAD

**Issue by abimlopas** [crazytuzi/UnrealCSharp#435]
被识别成Actor
![F3B73552C8060C4FCD4B6C4043CA1E6A](https://github.com/user-attachments/assets/85359c50-bcae-4b24-9a10-5e48ebf2de57)
![CA58B451188DECBA1330AEC6F42AFD87](https://github.com/user-attachments/assets/4a9bb9d2-f501-4d66-9ae9-f35658c2ddf5)
![7C1F9B501E5B179BEEC02D446E667C3A](https://github.com/user-attachments/assets/a9f90112-5ebc-4fe6-9b9c-206e27be8d94)
无法在编辑器中显示
![20241022-110012](https://github.com/user-attachments/assets/3f0ebda6-e4d8-4a22-8eda-0c8e3c78def2)
![20241022-110049](https://github.com/user-attachments/assets/2c4fc611-92b2-4e57-86c5-b259e9b71e54)

**Comment by crazytuzi** [comment]
默认Placeholder基类为AActor，错误识别为AActor，说明只走了Placeholder流程，并未走实际数据填充流程，本地环境有问题，多参考文档。

**Comment by abimlopas** [comment]
> 默认Placeholder基类为AActor，错误识别为AActor，说明只走了Placeholder流程，并未走实际数据填充流程，本地环境有问题，多参考文档。

我增加了一个手动编译的按钮
![image](https://github.com/user-attachments/assets/5d313276-d2ad-47ca-a221-cac832c82962)
![image](https://github.com/user-attachments/assets/e0bf0e51-3391-495b-a531-9d2ebb146244)
这样能否手动触发Weavers，或者你有什么更好的建议，可以在Weavers没自动触发时可以是手动触发下
还增加了一个选项是否忽略本地已存在的.sln文件，如果不忽略的话，导出的时候就不会覆盖本地已有的.sln文件
![image](https://github.com/user-attachments/assets/d13bfd96-334b-46a3-a8ec-ecdd907e39af)
![image](https://github.com/user-attachments/assets/7afc2470-6a6b-46ba-81fd-28592e6d8613)
这种做法是否会有潜在的问题

**Comment by crazytuzi** [comment]
- 没有触发编译过程是代表流程出问题了，应该去排查为啥出问题，而不是加一个手动编译
- 增加了一个选项是否忽略本地已存在的.sln文件，这是项目自定义拓展，自行做斟酌就行
