### ISSUE TITLE
C#中的UDataAsset在蓝图无法识别

### ISSUE THREAD

**Issue by abimlopas** [crazytuzi/UnrealCSharp#439]
![7255c0665009dc0c129720fc777ba8e9](https://github.com/user-attachments/assets/f5276089-7bc8-4432-936b-526557c45dc9)
![449b71d90474d043b818258fa9878683](https://github.com/user-attachments/assets/fc1690e0-cede-4290-99fd-40a5b6a7b17c)

**Comment by abimlopas** [comment]
![image](https://github.com/user-attachments/assets/5a2a9a05-e2ee-4751-bb0c-1da47f02a9af)
UObject下也没有，继承UPrimaryDataAsset也不行，而且从Pick Class 下选择的DataAsset是会被识别成Blueprint，使用起来会有问题
![image](https://github.com/user-attachments/assets/be5df5f1-1a1c-43bd-8a74-9ca34c28913d)
![image](https://github.com/user-attachments/assets/832adcb4-1c4f-495a-a909-5a4b527dfae4)

**Comment by crazytuzi** [comment]
这里的意思是，已知UPrimaryDataAsset是能够在Pick Parent Class中显示，所以参考UPrimaryDataAsset加上对应Meta，即Blueprintable，并非去继承UPrimaryDataAsset。
```csharp
using Script.Dynamic;
using Script.Engine;

namespace Script.CoreUObject
{
    [UClass, Blueprintable]
    public partial class UMyTestDataAsset : UDataAsset
    {
        [UProperty, EditAnywhere]
        public int Int32Value { get; set; }
    }
}
```
在Pick Parent Class中显示测试通过，能够正常新建DataAsset。

**Comment by abimlopas** [comment]
我用新工程测试没加Blueprintable也可以，
![image](https://github.com/user-attachments/assets/2038f868-3063-48a6-b966-9b5e108ce20f)
![image](https://github.com/user-attachments/assets/91ca74be-23c1-4525-aa7f-7b0004a6b017)
Character也出现过这种问题，后面我还是都加上Blueprintable吧
麻烦你了！
