### ISSUE TITLE
[Bug] 蓝图事件会自动导出，导致无法覆写

### ISSUE THREAD

**Issue by 1134451886** [crazytuzi/UnrealCSharp#455]
![image](https://github.com/user-attachments/assets/5e64e75d-cba4-4572-9eee-9fd57deb6247)
![image](https://github.com/user-attachments/assets/4e0ed740-30f6-4422-baf5-ca670735dbac)
经测试只要蓝图里的蓝图事件连有逻辑，就会导致事件被自动导出，进而无法覆写蓝图事件

**Comment by crazytuzi** [comment]
Proxy为生成文件，覆盖之后，下次就不会生成被覆盖的函数

**Comment by 1134451886** [comment]
需要手动删掉这个函数的声明然后再override覆盖，覆盖之后他会生成一个 private new void ReceiveTick()

**Comment by 1134451886** [comment]
是有意设计成这样的吗？

**Comment by crazytuzi** [comment]
是指ReceiveTick_Override吗，这个是被覆盖的函数，用来支持调用原始函数

**Comment by 1134451886** [comment]
明白了，也就是说这还是交互式生成，在C#代码中的写法也会影响生成结果
