### ISSUE TITLE
rider启动ue项目出现错误

### ISSUE THREAD

**Issue by wanghanghang0814** [crazytuzi/UnrealCSharp#466]
![屏幕截图 2024-11-26 155710](https://github.com/user-attachments/assets/c971d210-d5ff-42e1-9e91-abf5ef3d8080)

**Comment by crazytuzi** [comment]
为Rider bug，官方已修复，更新Rider到2024.3就行

**Comment by wanghanghang0814** [comment]
好的，感谢
