### ISSUE TITLE
C#动态类放到UE关卡后，重新打开UE项目，C#动态类会报资产失效

### ISSUE THREAD

**Issue by wanghanghang0814** [crazytuzi/UnrealCSharp#468]
皮皮好，我写了一个C#动态类，他继承于AActor，将这个动态类放到UE关卡后，再重新打开UE项目，这个动态蓝图会从关卡中消失，并会报资产失效日志：
LogWorldPartition: Warning: Invalid class for actor guid `312EFEC59EC47E2A15B4810B2587AF88` ('BP_CSharp_C') from package '/Game/BPs/BP_CSharp'
LogWorldPartition: Warning: Invalid class for actor guid `A7ADA25746E2A1EC445C9392E76FEA16` ('BP_CSharp_C_UAID_A83759A87DC3643302_1578274951') from package '/Game/__ExternalActors__/Maps/TestMap/B/63/T3AG6JLB54GIWWMYJJ3NSL'
LogWorldPartition: Warning: Invalid actor native class: Actor: 'BP_CSharp_C_UAID_A83759A87DC3643302_1578274951' (guid 'A7ADA25746E2A1EC445C9392E76FEA16') from package '/Game/__ExternalActors__/Maps/TestMap/B/63/T3AG6JLB54GIWWMYJJ3NSL'

点击如下错误修复：
![image](https://github.com/user-attachments/assets/309b805e-c01c-48c5-ae2f-89f3e24a14f0)
UE编辑器直接崩溃：
LoginId:2180ed64422e1f3fe9efe58507868576
EpicAccountId:579eb2e442e04c17b8a4fda80b95e35f

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x0000000000000018

UnrealEditor_UnrealCSharpCore!FUnrealCSharpFunctionLibrary::GetSuffixName() [D:\Unreal Projects\MyPlayerController\Plugins\UnrealCSharp-main\Source\UnrealCSharpCore\Private\Common\FUnrealCSharpFunctionLibrary.cpp:334]
UnrealEditor_UnrealCSharpCore!FUnrealCSharpFunctionLibrary::GetAssetName() [D:\Unreal Projects\MyPlayerController\Plugins\UnrealCSharp-main\Source\UnrealCSharpCore\Private\Common\FUnrealCSharpFunctionLibrary.cpp:343]
UnrealEditor_UnrealCSharpCore!FUnrealCSharpFunctionLibrary::GetFileName() [D:\Unreal Projects\MyPlayerController\Plugins\UnrealCSharp-main\Source\UnrealCSharpCore\Private\Common\FUnrealCSharpFunctionLibrary.cpp:384]
UnrealEditor_UnrealCSharpCore!FUnrealCSharpFunctionLibrary::GetFileName() [D:\Unreal Projects\MyPlayerController\Plugins\UnrealCSharp-main\Source\UnrealCSharpCore\Private\Common\FUnrealCSharpFunctionLibrary.cpp:375]
UnrealEditor_UnrealCSharpEditor!`FEditorListener::OnAssetRemoved'::`2'::<lambda_1>::operator()() [D:\Unreal Projects\MyPlayerController\Plugins\UnrealCSharp-main\Source\UnrealCSharpEditor\Private\Listener\FEditorListener.cpp:209]
UnrealEditor_UnrealCSharpEditor!FEditorListener::OnAssetRemoved() [D:\Unreal Projects\MyPlayerController\Plugins\UnrealCSharp-main\Source\UnrealCSharpEditor\Private\Listener\FEditorListener.cpp:207]
UnrealEditor_UnrealCSharpEditor!TBaseRawMethodDelegateInstance<1,FEditorListener const ,void __cdecl(FAssetData const &),FDefaultTSDelegateUserPolicy>::ExecuteIfSafe() [D:\Epic Games\UE_5.4\Engine\Source\Runtime\Core\Public\Delegates\DelegateInstancesImpl.h:535]
UnrealEditor_AssetRegistry!UAssetRegistryImpl::Broadcast() [D:\build\++UE5\Sync\Engine\Source\Runtime\AssetRegistry\Private\AssetRegistry.cpp:7879]
UnrealEditor_AssetRegistry!UAssetRegistryImpl::OnDirectoryChanged() [D:\build\++UE5\Sync\Engine\Source\Runtime\AssetRegistry\Private\AssetRegistry.cpp:6174]
UnrealEditor_AssetRegistry!V::TBaseUObjectMethodDelegateInstance::Execute() [D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Public\Delegates\DelegateInstancesImpl.h:650]
UnrealEditor_DirectoryWatcher!FDirectoryWatchRequestWindows::ProcessPendingNotifications() [D:\build\++UE5\Sync\Engine\Source\Developer\DirectoryWatcher\Private\Windows\DirectoryWatchRequestWindows.cpp:179]
UnrealEditor_DirectoryWatcher!FDirectoryWatcherWindows::Tick() [D:\build\++UE5\Sync\Engine\Source\Developer\DirectoryWatcher\Private\Windows\DirectoryWatcherWindows.cpp:120]
UnrealEditor_DirectoryWatcher!FDirectoryWatcherProxy::Tick() [D:\build\++UE5\Sync\Engine\Source\Developer\DirectoryWatcher\Private\DirectoryWatcherProxy.cpp:66]
UnrealEditor_UnrealEd!UEditorEngine::Tick() [D:\build\++UE5\Sync\Engine\Source\Editor\UnrealEd\Private\EditorEngine.cpp:1789]
UnrealEditor_UnrealEd!UUnrealEdEngine::Tick() [D:\build\++UE5\Sync\Engine\Source\Editor\UnrealEd\Private\UnrealEdEngine.cpp:550]
UnrealEditor!FEngineLoop::Tick() [D:\build\++UE5\Sync\Engine\Source\Runtime\Launch\Private\LaunchEngineLoop.cpp:5921]
UnrealEditor!GuardedMain() [D:\build\++UE5\Sync\Engine\Source\Runtime\Launch\Private\Launch.cpp:180]
UnrealEditor!GuardedMainWrapper() [D:\build\++UE5\Sync\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:118]
UnrealEditor!LaunchWindowsStartup() [D:\build\++UE5\Sync\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:258]
UnrealEditor!WinMain() [D:\build\++UE5\Sync\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:298]
UnrealEditor!__scrt_common_main_seh() [D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288]
kernel32
ntdll

**Comment by crazytuzi** [comment]
具体动态类C#代码是什么，是不是namespace没对

**Comment by wanghanghang0814** [comment]
`
using Script.Dynamic;
using Script.Engine;
namespace Script.CoreUObject;

[UClass]
public partial class CSharpActor_C : AActor
{
    public CSharpActor_C()
    {
        PrimaryActorTick.bCanEverTick = true;
    }

    [Override]
    public override void ReceiveTick(float DeltaSeconds)
    {
        base.ReceiveTick(DeltaSeconds);
        UKismetSystemLibrary.PrintString(this, "csharp tick...");
    }
}
`
是一个很普通的actor子类，我让他作为蓝图类BP_CSharp的父类，将BP_CSharp放到关卡中保存后，重新打开ue编辑器，关卡中这个动态蓝图会消失，并报下面提示：

![image](https://github.com/user-attachments/assets/648a3c6e-e7cc-4509-92bf-19094eb96042)

LogWorldPartition: Warning: Invalid class for actor guid `312EFEC59EC47E2A15B4810B2587AF88` ('BP_CSharp_C') from package '/Game/BPs/BP_CSharp'
LogWorldPartition: Warning: Invalid class for actor guid `16BE60F343A4156086BCF4A2066366C3` ('BP_CSharp_C_UAID_A83759A87DC3B33302_2002421855') from package '/Game/__ExternalActors__/FirstPerson/Maps/FirstPersonMap/3/GD/BNQAMBD6WM0KVPQT7U67S6'
LogWorldPartition: Warning: Invalid actor native class: Actor: 'BP_CSharp_C_UAID_A83759A87DC3B33302_2002421855' (guid '16BE60F343A4156086BCF4A2066366C3') from package '/Game/__ExternalActors__/FirstPerson/Maps/FirstPersonMap/3/GD/BNQAMBD6WM0KVPQT7U67S6'
LogWorldPartition: Warning: Invalid class for actor guid `EF88381645938B05B75DB3918A683810` ('BP_CSharp_C_UAID_A83759A87DC3B33302_2120991855') from package '/Game/__ExternalActors__/FirstPerson/Maps/FirstPersonMap/5/UD/BT9RQMCW8PUA4KFAGGNA4T'
LogWorldPartition: Warning: Invalid actor native class: Actor: 'BP_CSharp_C_UAID_A83759A87DC3B33302_2120991855' (guid 'EF88381645938B05B75DB3918A683810') from package '/Game/__ExternalActors__/FirstPerson/Maps/FirstPersonMap/5/UD/BT9RQMCW8PUA4KFAGGNA4T'

我目前遇到是，自定义的C#动态蓝图，在UE关卡中保存是无效的，下次打开关卡仍然需要手动再放到关卡中

**Comment by crazytuzi** [comment]
这个情况之前已经处理过，确认下动态类是不是生成失败了

**Comment by crazytuzi** [comment]
限制主要在引擎，以5.0为例[ActorDescContainer](https://github.com/EpicGames/UnrealEngine/blob/5.0/Engine/Source/Runtime/Engine/Private/WorldPartition/ActorDescContainer.cpp#L72)，FindObject最后一个参数为true，限制了必须为UClass，解决方案如下：

1. 使用WP地图时，需要放置到场景中时，避免继承链中出现动态蓝图类，经测试，动态C++类是可以的
2. 如果可以修改引擎，修改上边提到的代码，将最后一个参数改为false即可

**Comment by wanghanghang0814** [comment]
好的，这个我再看看，感谢皮佬
