### ISSUE TITLE
[BUG] Unreal freeze.

### ISSUE THREAD

**Issue by PourrezJ** [crazytuzi/UnrealCSharp#87]
Hello,

I'm experiencing an issue with the use of the C# plugin for Unreal. I have successfully installed the plugin, but as soon as I press the "Play" button to launch the project, Unreal freezes and becomes unresponsive.

I have tried uninstalling and reinstalling the plugin, but the issue persists. I have tested this issue with both Unreal versions 5.1.1 and 5.0.3, and have verified that the plugin's minimum requirements are met.

Do you have any advice or suggestions for resolving this problem?

Thank you in advance for your help.

Best regards

**Comment by crazytuzi** [comment]
When you first use this plugin, you should follow the instructions in the image to generate a C # project.
![275d21d1bbb82e20760414a7f8525f12](https://user-images.githubusercontent.com/28628663/230131243-495aba77-7e21-4319-be68-5f9bba9185f1.png)

**Comment by PourrezJ** [comment]
I get the same result.

**Comment by crazytuzi** [comment]
Comment out the function body and try again.
![QQ图片20230406121129](https://user-images.githubusercontent.com/28628663/230270308-29d1d3cf-cd59-414d-b137-4036d1258c45.png)

**Comment by PourrezJ** [comment]
After commenting out the loop, now when I press play, the editor closes without any error message.

**Comment by crazytuzi** [comment]
This plug-in is still in the development stage, and no detailed access documentation has been provided for the time being. If you are interested in improving this plugin together, you can join us.

**Comment by PourrezJ** [comment]
I get a problem, the GetCompileTool function does not return any result even though vswhere.exe is not null. The while loop does not iterate and the Result variable is empty. This occurs even if the vswhere.exe command is executed correctly in a terminal.

I have verified that vswhere.exe is installed on my system and that the parameters for the vswhere.exe command are correct. I have also verified that the access rights are sufficient to execute vswhere.exe.

I have added debugging messages to understand the problem, but I have not been able to find the cause of the problem.

**Comment by crazytuzi** [comment]
I just refer to the following two links, are you using vs2019.

1. [Tools for detecting and managing Visual Studio instances](https://learn.microsoft.com/en-us/visualstudio/install/tools-for-managing-visual-studio-instances?view=vs-2022)

2. [Unable to Locate Visual Studio 2019 Registry Path](https://social.msdn.microsoft.com/Forums/en-US/f4597432-b891-4005-82f3-b3279a1868ac/unable-to-locate-visual-studio-2019-registry-path?forum=visualstudiogeneral)
