### ISSUE TITLE
[Bug] System.Action`9 Exception

### ISSUE THREAD

**Issue by KarryCharon** [crazytuzi/UnrealCSharp#98]
Could not load signature of Script.Engine.AActor:get_OnTakePointDamage due to: Could not resolve type with token 01000037 from typeref (expected class 'System.Action`9' in assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51') assembly:netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 type:System.Action`9 member:(null)
Exception: Exception 0xc0000005 encountered at address 0x7ffb5df2dbb8: Access violation reading location 0x0000000c

**Comment by crazytuzi** [comment]
@JomiXedYu
